ci: require cuda test (#361)
Co-authored-by: pre-commit-ci-lite[bot] <117423508+pre-commit-ci-lite[bot]@users.noreply.github.com>

diff --git a/.github/workflows/ci-python-cuda.yml b/.github/workflows/ci-python-cuda.yml
--- a/.github/workflows/ci-python-cuda.yml
+++ b/.github/workflows/ci-python-cuda.yml
@@ -7,10 +7,30 @@ on:
       release:
         type: boolean
         default: false
+      event:
+        type: string
+        required: true
 permissions: read-all
 env:
   PYTHON_CUDA_ROOT: ${{github.workspace}}/python-cuda
 jobs:
+  check-test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        if: ${{github.event_name == 'pull_request'}}
+      - id: change
+        uses: tj-actions/changed-files@v46
+        if: ${{github.event_name == 'pull_request'}}
+        with:
+          files: |
+            ${{!env.PYTHON_CUDA_ROOT}}/junit.xml
+            ${{!env.PYTHON_CUDA_ROOT}}/coverage.xml
+
+      - if: ${{steps.change.outputs.all_modified  != 'true'}}
+        run: |
+          echo "::error title=Test Report Outdated::Run test on local machine and update the test report."
+          exit 1
   rattler-build:
     env:
       PYTEST_ADDOPTS: "--color=yes"
diff --git a/.github/workflows/ci-rust-cuda.yml b/.github/workflows/ci-rust-cuda.yml
--- a/.github/workflows/ci-rust-cuda.yml
+++ b/.github/workflows/ci-rust-cuda.yml
@@ -7,6 +7,9 @@ on:
       release:
         type: boolean
         default: false
+      event:
+        type: string
+        required: true
 
 permissions: read-all
 
@@ -14,6 +17,22 @@ env:
   RUST_CUDA_ROOT: ./rust-cuda
 
 jobs:
+  check-test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        if: ${{github.event_name == 'pull_request'}}
+      - id: change
+        uses: tj-actions/changed-files@v46
+        if: ${{github.event_name == 'pull_request'}}
+        with:
+          files: |
+            ${{!env.RUST_CUDA_ROOT}}/lcov.info
+            ${{!env.RUST_CUDA_ROOT}}/nextest.junit.xml
+      - if: ${{steps.change.outputs.all_modified  != 'true'}}
+        run: |
+          echo "::error title=Test Report Outdated::Run test on local machine and update the test report."
+          exit 1
   upload-cov:
     if: ${{!inputs.release}}
     strategy:
